### PR TITLE
[WIP] Navigation Drawer

### PR DESCRIPTION
**Pull request by egeldenhuys**
Implemented according to #63. Currently WIP, discussion will follow.

### CODE REVIEW

**Comment by egeldenhuys** [comment]
For now I think the drawer should be implemented as a static panel on the left.

HyperLinks were used in the screenshot below.
drawer

**Comment by RagingGrim** [comment]
I suppose if it works it works? xD

**Comment by egeldenhuys** [comment]
I am having problems getting the `wxDataViewTreeCtrl` object to fit its contents. Does anybody have a suggestion?

**Comment by egeldenhuys** [comment]
This attempt failed horribly. I wonder what happens to the pull request when the branch is deleted?

**Comment by egeldenhuys** [comment]
Waiting for garbage collector I guess

**Comment by egeldenhuys** [comment]
Perhaps [WIP] pull requests are not so useful

**Pull request closed without merging**
