### PR TITLE
Issue148

### PR DESCRIPTION
**Pull request by CDuPlooy**

### CODE REVIEW

**Comment by RagingGrim** [comment]
Make sure to make clean; make before testing this.

Useful tricks for quickly checking if it works.
```
#undef __unix__
#define __APPLE__ 1
```

**Comment by egeldenhuys** [comment]
The tabs are now being displayed on mac, looks better than our custom buttons.

macky

**Review by egeldenhuys — APPROVED** [review]
Looks good!

**Comment by egeldenhuys** [comment]
Closes #148

**Pull request merged**
